stages:
  - build
  - test
  - deploy

# Backend build job
build-backend:
  stage: build
  image: node:16
  script:
    - echo "Building the backend"
    - cd backend
    - npm install
    - npm run build
  tags:
    - ci
    - backend

# Frontend build job
build-frontend:
  stage: build
  image: node:16
  script:
    - echo "Building the frontend"
    - cd frontend
    - npm install
    - npm run build
  tags:
    - ci
    - frontend

# Backend test job
test-backend:
  stage: test
  image: node:16
  script:
    - echo "Running backend tests"
    - cd backend
    - npm install
    - npm test
  tags:
    - ci
    - backend

# Frontend test job
test-frontend:
  stage: test
  image: node:16
  script:
    - echo "Running frontend tests"
    - cd frontend
    - npm install
    - npm test
  tags:
    - ci
    - frontend

# Deployment job
deploy:
  stage: deploy
  image: docker:20.10.7
  services:
    - docker:20.10.7-dind
  script:
    - echo "Deploying the project"
    - docker-compose up -d --build
  tags:
    - ci
    - deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != 'merge_request_event'
