version: '4'
services:
  backend:
    build:
      context: backend
    container_name: backend
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./frontend
    container_name: frontend_ts
    ports:
      - "3000:3000"